DROP TABLE IF EXISTS author_book
DROP TABLE IF EXISTS employee_store
DROP TABLE IF EXISTS order_details
DROP TABLE IF EXISTS inventory
DROP TABLE IF EXISTS authors
DROP TABLE IF EXISTS books
DROP TABLE IF EXISTS orders
DROP TABLE IF EXISTS stores
DROP TABLE IF EXISTS employees
DROP TABLE IF EXISTS customers

DROP FUNCTION IF EXISTS dbo.fn_verify_isbn13

DROP VIEW IF EXISTS titles_by_author